<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="iverksattVedtakBehandling" targetNamespace="http://nav.no/domene/pensjon/tjenester/iverksattVedtakBehandling/v1" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/domene/pensjon/tjenester/iverksattVedtakBehandling/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema targetNamespace="http://nav.no/domene/pensjon/tjenester/iverksattVedtakBehandling/v1" xmlns:meldinger="http://nav.no/domene/pensjon/tjenester/iverksattVedtakBehandling/meldinger/v1">
      <xsd:import namespace="http://nav.no/domene/pensjon/tjenester/iverksattVedtakBehandling/meldinger/v1" schemaLocation="meldinger/meldinger.xsd"/>
      <xsd:element name="endreIverksattVedtak">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="request" type="meldinger:EndreIverksattVedtakRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="endreIverksattVedtakResponse">
        <xsd:complexType>
          <xsd:sequence>
            
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="endreIverksattVedtakRequest">
    <wsdl:part name="parameters" element="tns:endreIverksattVedtak">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="endreIverksattVedtakResponse">
    <wsdl:part name="parameters" element="tns:endreIverksattVedtakResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="IverksattVedtakBehandling">
    <wsdl:operation name="endreIverksattVedtak">
<wsdl:documentation>&lt;p&gt;Operasjonen benyttes til å stoppe, eller reaktivere et iverksatt vedtak. &lt;/p&gt;&lt;p&gt;Den kaller iverksetting for å generere opp oppdragsmelding som sendes asynkront videre til PPEN016. &lt;/p&gt; </wsdl:documentation>
      <wsdl:input message="tns:endreIverksattVedtakRequest">
    </wsdl:input>
      <wsdl:output message="tns:endreIverksattVedtakResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
