<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PSELVUtbetalingWSEXP_PSELVUtbetalingHttp_Service" targetNamespace="http://nav-cons-pen-pselv-utbetaling/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-pselv-utbetaling/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pselv-utbetaling/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-pselv-utbetaling/no/nav/inf" location="no/nav/inf/PSELVUtbetaling.wsdl">
    </wsdl:import>
  <wsdl:binding name="PSELVUtbetalingWSEXP_PSELVUtbetalingHttpBinding" type="Port_0:PSELVUtbetaling">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentUtbetalingListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentUtbetalingListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentUtbetalingListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentPeriodisertUtbetalingListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentPeriodisertUtbetalingListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentPeriodisertUtbetalingListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PSELVUtbetalingWSEXP_PSELVUtbetalingHttpService">
    <wsdl:port name="PSELVUtbetalingWSEXP_PSELVUtbetalingHttpPort" binding="this:PSELVUtbetalingWSEXP_PSELVUtbetalingHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-pselv-utbetalingWeb/sca/PSELVUtbetalingWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
