<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PSELVPPEN003WSEXP_PSELVPPEN003Http_Service" targetNamespace="http://nav-cons-pen-pselv-ppen003/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-pselv-ppen003/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pselv-ppen003/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-pselv-ppen003/no/nav/inf" location="no/nav/inf/PSELVPPEN003.wsdl">
    </wsdl:import>
  <wsdl:binding name="PSELVPPEN003WSEXP_PSELVPPEN003HttpBinding" type="Port_0:PSELVPPEN003">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="behandleFleksibelAPSak">
      <soap:operation soapAction=""/>
      <wsdl:input name="behandleFleksibelAPSakRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="behandleFleksibelAPSakResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PSELVPPEN003WSEXP_PSELVPPEN003HttpService">
    <wsdl:port name="PSELVPPEN003WSEXP_PSELVPPEN003HttpPort" binding="this:PSELVPPEN003WSEXP_PSELVPPEN003HttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-pselv-ppen003Web/sca/PSELVPPEN003WSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
