<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PENPPEN003WSEXP_PENPPEN003Http_Service" targetNamespace="http://nav-cons-pen-pen-ppen003/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-pen-ppen003/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pen-ppen003/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-pen-ppen003/no/nav/inf" location="no/nav/inf/PENPPEN003.wsdl">
    </wsdl:import>
  <wsdl:binding name="PENPPEN003WSEXP_PENPPEN003HttpBinding" type="Port_0:PENPPEN003">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="behandleKompletteringAvGrunnlag">
      <soap:operation soapAction=""/>
      <wsdl:input name="behandleKompletteringAvGrunnlagRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="behandleKompletteringAvGrunnlagResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PENPPEN003WSEXP_PENPPEN003HttpService">
    <wsdl:port name="PENPPEN003WSEXP_PENPPEN003HttpPort" binding="this:PENPPEN003WSEXP_PENPPEN003HttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-pen-ppen003Web/sca/PENPPEN003WSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
