<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-cons-pen-pen-vedtak/no/nav/inf/PENVedtak" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pen-vedtak/no/nav/inf/PENVedtak/Binding" name="PENVedtakWSEXP_PENVedtakHttp_Service" targetNamespace="http://nav-cons-pen-pen-vedtak/no/nav/inf/PENVedtak/Binding">
  <wsdl:import location="no/nav/inf/PENVedtak.wsdl" namespace="http://nav-cons-pen-pen-vedtak/no/nav/inf/PENVedtak"/>
  <wsdl:binding name="PENVedtakWSEXP_PENVedtakHttpBinding" type="Port_0:PENVedtak">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendStoppEllerReaktiviserOppdragsmelding">
      <soap:operation soapAction=""/>
      <wsdl:input name="sendStoppEllerReaktiviserOppdragsmeldingRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PENVedtakWSEXP_PENVedtakHttpService">
    <wsdl:port binding="this:PENVedtakWSEXP_PENVedtakHttpBinding" name="PENVedtakWSEXP_PENVedtakHttpPort">
      <soap:address location="http://localhost:9080/nav-cons-pen-pen-vedtakWeb/sca/PENVedtakWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
