<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PENInntektWSEXP_PENInntektHttp_Service" targetNamespace="http://nav-cons-pen-pen-inntekt/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-pen-inntekt/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pen-inntekt/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-pen-inntekt/no/nav/inf" location="no/nav/inf/PENInntekt.wsdl">
    </wsdl:import>
  <wsdl:binding name="PENInntektWSEXP_PENInntektHttpBinding" type="Port_0:PENInntekt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentInntektListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentInntektListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentInntektListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PENInntektWSEXP_PENInntektHttpService">
    <wsdl:port name="PENInntektWSEXP_PENInntektHttpPort" binding="this:PENInntektWSEXP_PENInntektHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-pen-inntektWeb/sca/PENInntektWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
