<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PENPPEN006WSEXP_PENPPEN006Http_Service" targetNamespace="http://nav-cons-pen-pen-ppen006/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-pen-ppen006/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pen-ppen006/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-pen-ppen006/no/nav/inf" location="no/nav/inf/PENPPEN006.wsdl">
    </wsdl:import>
  <wsdl:binding name="PENPPEN006WSEXP_PENPPEN006HttpBinding" type="Port_0:PENPPEN006">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="behandleAfpPrivat">
      <soap:operation soapAction=""/>
      <wsdl:input name="behandleAfpPrivatRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="behandleAfpPrivatResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PENPPEN006WSEXP_PENPPEN006HttpService">
    <wsdl:port name="PENPPEN006WSEXP_PENPPEN006HttpPort" binding="this:PENPPEN006WSEXP_PENPPEN006HttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-pen-ppen006Web/sca/PENPPEN006WSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
