<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PSAKInstitusjonsoppholdWSEXP_PSAKInstitusjonsoppholdHttp_Service" targetNamespace="http://nav-cons-pen-psak-institusjonsopphold/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-psak-institusjonsopphold/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-psak-institusjonsopphold/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-psak-institusjonsopphold/no/nav/inf" location="no/nav/inf/PSAKInstitusjonsopphold.wsdl">
    </wsdl:import>
  <wsdl:binding name="PSAKInstitusjonsoppholdWSEXP_PSAKInstitusjonsoppholdHttpBinding" type="Port_0:PSAKInstitusjonsopphold">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="lagreInstitusjonsopphold">
      <soap:operation soapAction=""/>
      <wsdl:input name="lagreInstitusjonsoppholdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="lagreInstitusjonsoppholdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenOppholdPeriodeIdIkkeFunnet">
        <soap:fault name="faultPenOppholdPeriodeIdIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultPenFnrIkkeFunnet">
        <soap:fault name="faultPenFnrIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opprettInstitusjonsopphold">
      <soap:operation soapAction=""/>
      <wsdl:input name="opprettInstitusjonsoppholdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opprettInstitusjonsoppholdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenFnrIkkeFunnet">
        <soap:fault name="faultPenFnrIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="slettInstitusjonsopphold">
      <soap:operation soapAction=""/>
      <wsdl:input name="slettInstitusjonsoppholdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="slettInstitusjonsoppholdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenInstitusjonsoppholdIkkeFunnet">
        <soap:fault name="faultPenInstitusjonsoppholdIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PSAKInstitusjonsoppholdWSEXP_PSAKInstitusjonsoppholdHttpService">
    <wsdl:port name="PSAKInstitusjonsoppholdWSEXP_PSAKInstitusjonsoppholdHttpPort" binding="this:PSAKInstitusjonsoppholdWSEXP_PSAKInstitusjonsoppholdHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-psak-institusjonsoppholdWeb/sca/PSAKInstitusjonsoppholdWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
