<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PSAKFullmaktWSEXP_PSAKFullmaktHttp_Service" targetNamespace="http://nav-cons-pen-psak-fullmakt/no/nav/inf/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-cons-pen-psak-fullmakt/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-psak-fullmakt/no/nav/inf/Binding">
  <import namespace="http://nav-cons-pen-psak-fullmakt/no/nav/inf" location="no/nav/inf/PSAKFullmakt.wsdl">
    </import>
  <binding name="PSAKFullmaktWSEXP_PSAKFullmaktHttpBinding" type="Port_0:PSAKFullmakt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="hentFullmaktListe">
      <soap:operation/>
      <input name="hentFullmaktListeRequest">
        <soap:body use="literal"/>
      </input>
      <output name="hentFullmaktListeResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </fault>
    </operation>
    <operation name="lagreFullmakt">
      <soap:operation/>
      <input name="lagreFullmaktRequest">
        <soap:body use="literal"/>
      </input>
      <output name="lagreFullmaktResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultPenFullmaktIkkeFunnet">
        <soap:fault name="faultPenFullmaktIkkeFunnet" use="literal"/>
      </fault>
      <fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </fault>
    </operation>
    <operation name="opprettFullmakt">
      <soap:operation/>
      <input name="opprettFullmaktRequest">
        <soap:body use="literal"/>
      </input>
      <output name="opprettFullmaktResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </fault>
    </operation>
    <operation name="slettFullmakt">
      <soap:operation/>
      <input name="slettFullmaktRequest">
        <soap:body use="literal"/>
      </input>
      <output name="slettFullmaktResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultPenFullmaktIkkeFunnet">
        <soap:fault name="faultPenFullmaktIkkeFunnet" use="literal"/>
      </fault>
      <fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="PSAKFullmaktWSEXP_PSAKFullmaktHttpService">
    <port name="PSAKFullmaktWSEXP_PSAKFullmaktHttpPort" binding="this:PSAKFullmaktWSEXP_PSAKFullmaktHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-psak-fullmaktWeb/sca/PSAKFullmaktWSEXP"/>
    </port>
  </service>
</definitions>
