<?xml version="1.0" encoding="UTF-8"?>
<definitions name="PSAKArenasakWSEXP_PSAKArenasakHttp_Service" targetNamespace="http://nav-cons-pen-psak-arenasak/no/nav/inf/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-cons-pen-psak-arenasak/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-psak-arenasak/no/nav/inf/Binding">
  <import namespace="http://nav-cons-pen-psak-arenasak/no/nav/inf" location="no/nav/inf/PSAKArenasak.wsdl">
    </import>
  <binding name="PSAKArenasakWSEXP_PSAKArenasakHttpBinding" type="Port_0:PSAKArenasak">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="hentSaksInfoListe">
      <soap:operation/>
      <input name="hentSaksInfoListeRequest">
        <soap:body use="literal"/>
      </input>
      <output name="hentSaksInfoListeResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="PSAKArenasakWSEXP_PSAKArenasakHttpService">
    <port name="PSAKArenasakWSEXP_PSAKArenasakHttpPort" binding="this:PSAKArenasakWSEXP_PSAKArenasakHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-psak-arenasakWeb/sca/PSAKArenasakWSEXP"/>
    </port>
  </service>
</definitions>
