<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/sak/Binding/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/virksomhet/tjenester/sak/Binding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sak="http://nav.no/virksomhet/tjenester/sak/v1">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/sak/v1" location="../sak.wsdl">
    </wsdl:import>
  <wsdl:binding name="SakBinding" type="sak:Sak">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="finnGenerellSakListe">
      <soap:operation soapAction="http://nav.no/virksomhet/tjenester/sak/v1/Sak/finnGenerellSakListeRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Sak">
    <wsdl:port name="SakPort" binding="tns:SakBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-sak_v1Web/sca/SakWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
