<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PENOppdragBatchWSEXP_PENOppdragBatchHttp_Service" targetNamespace="http://nav-cons-pen-pen-batch-oppdrag/no/nav/inf/Binding" xmlns:Port_0="http://nav-cons-pen-pen-batch-oppdrag/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav-cons-pen-pen-batch-oppdrag/no/nav/inf/Binding">
  <wsdl:import namespace="http://nav-cons-pen-pen-batch-oppdrag/no/nav/inf" location="no/nav/inf/PENOppdragBatch.wsdl">
    </wsdl:import>
  <wsdl:binding name="PENOppdragBatchWSEXP_PENOppdragBatchHttpBinding" type="Port_0:PENOppdragBatch">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sendAsynkronOppdragsmeldingListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="sendAsynkronOppdragsmeldingListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendAsynkronOppdragsmeldingListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="sendAsynkronOppdragsavstemmingListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="sendAsynkronOppdragsavstemmingListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sendAsynkronOppdragsavstemmingListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPenGenerisk">
        <soap:fault name="faultPenGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PENOppdragBatchWSEXP_PENOppdragBatchHttpService">
    <wsdl:port name="PENOppdragBatchWSEXP_PENOppdragBatchHttpPort" binding="this:PENOppdragBatchWSEXP_PENOppdragBatchHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-pen-pen-batch-oppdragWeb/sca/PENOppdragBatchWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
