name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
