name: Release (Github Package Registry)

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Package
        run: mvn verify -B --settings maven-settings-github.xml  -Dsurefire.rerunFailingTestsCount=3

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: .github/deploy.sh
